# Generated by Django 4.2.1 on 2023-06-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_historicalindicador_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryproduct',
            name='mesure_unit',
        ),
        migrations.RemoveField(
            model_name='historicalcategoryproduct',
            name='mesure_unit',
        ),
        migrations.AddField(
            model_name='historicalproduct',
            name='mesure_unit',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.measureunit', verbose_name='Unidad de medida'),
        ),
        migrations.AddField(
            model_name='product',
            name='mesure_unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.measureunit', verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='historicalproduct',
            name='category_product',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='products.categoryproduct', verbose_name='Categoría de Producto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.categoryproduct', verbose_name='Categoría de Producto'),
        ),
    ]
